import type { TemplateConfig } from "../../types/template-engine";

export const elegantWeddingConfig: TemplateConfig = {
  id: "elegant-wedding",
  name: "Elegant Wedding",
  description: "Template mewah dengan nuansa gold dan gelap yang dramatis, cocok untuk pernikahan formal malam hari.",
  category: "wedding",
  previewImage: "/images/preview-elegant.jpg",
  isPremium: true,
  colors: {
    primary: "#C9A96E",
    secondary: "#2C2420",
    background: "#0D0A08",
    text: "#F5EFE3",
    accent: "#E8D5B0",
    surface: "#1A1512",
    muted: "#9E7A3E",
  },
  fonts: {
    heading: "Playfair Display",
    body: "Inter",
    quote: "Great Vibes",
  },
  ornaments: [
    { id: "header-gold", type: "svg", position: "header", src: "/ornament/header-01.svg" },
    { id: "footer-gold", type: "svg", position: "footer", src: "/ornament/header-04.svg" },
    { id: "divider-line", type: "svg", position: "divider", svg: "<svg width='200' height='2' viewBox='0 0 200 2'><line x1='0' y1='1' x2='200' y2='1' stroke='#C9A96E' stroke-width='0.5'/></svg>" },
    { id: "corner-decor", type: "svg", position: "corner", src: "/ornament/header-11.svg" },
  ],
  animation: {
    sectionEntrance: "fade-up",
    staggerDelay: 0.15,
    duration: 0.8,
    parallax: true,
  },
  sections: [
    { type: "opening", enabled: true, label: "Pembukaan", icon: "DoorOpen", customizable: true, fields: [] },
    { type: "hero", enabled: true, label: "Hero", icon: "Heart", customizable: true, fields: ["brideName", "groomName", "heroImage"] },
    { type: "quote", enabled: true, label: "Kutipan", icon: "Quote", customizable: true, fields: [] },
    { type: "countdown", enabled: true, label: "Countdown", icon: "Timer", customizable: true, fields: ["eventDate"] },
    { type: "story", enabled: true, label: "Kisah Cinta", icon: "ScrollText", customizable: true, fields: ["story"] },
    { type: "gallery", enabled: true, label: "Galeri", icon: "ImageIcon", customizable: true, fields: ["gallery"] },
    { type: "event", enabled: true, label: "Acara", icon: "CalendarHeart", customizable: true, fields: ["eventDate", "eventTime", "eventLocation", "googleMapsUrl"] },
    { type: "rsvp", enabled: true, label: "RSVP", icon: "BadgeCheck", customizable: true, fields: [] },
    { type: "wishes", enabled: true, label: "Ucapan", icon: "MessageCircleHeart", customizable: true, fields: [] },
    { type: "gift", enabled: true, label: "Hadiah", icon: "Gift", customizable: true, fields: ["giftBankName", "giftAccountNumber", "giftAccountName"] },
    { type: "live-streaming", enabled: false, label: "Live Streaming", icon: "Radio", customizable: true, fields: [] },
    { type: "footer", enabled: true, label: "Penutup", icon: "PartyPopper", customizable: true, fields: [] },
  ],
  opening: {
    enabled: true,
    backgroundType: "gradient",
    backgroundValue: "linear-gradient(160deg, #0D0A08, #2C2420)",
    overlayOpacity: 0.3,
    ornamentPosition: "center",
    buttonLabel: "Buka Undangan",
    buttonStyle: "solid",
    showNames: true,
    showDate: true,
    showEyebrow: true,
    eyebrowText: "The Wedding of",
  },
  border: { radius: "0.75rem", style: "rounded" },
  buttonStyle: "solid",
  gradientFrom: "#0D0A08",
  gradientTo: "#2C2420",
};
