import type { ThemeConfig } from "../../types/template";

export const elegantWeddingV2Config: ThemeConfig = {
  id: "elegant-wedding",
  name: "Elegant Wedding",
  description: "Tema dark mewah dengan aksen emas klasik — cocok untuk undangan pernikahan formal dan elegan.",
  category: "elegan",
  version: "1.0.0",
  author: "Kundangan",
  previewImage: "/images/preview-elegant.jpg",
  isPremium: true,
  colors: {
    primary: "#C9A96E",
    secondary: "#2C2420",
    background: "#0D0A08",
    text: "#F5EFE3",
    accent: "#E8D5B0",
    surface: "#1A1512",
    muted: "#9E7A3E",
  },
  fonts: {
    heading: "Playfair Display",
    body: "Inter",
    quote: "Great Vibes",
  },
  animations: {
    cover: "fade-up",
    content: "fade-up",
    gallery: "fade-up",
    couple: "fade-up",
  },
  decorations: {
    enabled: ["flower-corner", "sparkle"],
    intensity: "medium",
    color: "#C9A96E",
  },
  sections: [
    { type: "cover", enabled: true, label: "Cover", order: 0 },
    { type: "couple", enabled: true, label: "Kedua Mempelai", order: 1 },
    { type: "countdown", enabled: true, label: "Hitung Mundur", order: 2 },
    { type: "story", enabled: true, label: "Cerita Kami", order: 3 },
    { type: "gallery", enabled: true, label: "Galeri Foto", order: 4 },
    { type: "event", enabled: true, label: "Acara", order: 5 },
    { type: "rsvp", enabled: true, label: "Konfirmasi Kehadiran", order: 6 },
    { type: "wish", enabled: true, label: "Ucapan & Doa", order: 7 },
    { type: "gift", enabled: true, label: "Hadiah", order: 8 },
    { type: "footer", enabled: true, label: "Penutup", order: 9 },
  ],
  cover: {
    backgroundType: "gradient",
    backgroundValue: "linear-gradient(160deg, #0D0A08, #2C2420)",
    overlayOpacity: 0.3,
    ornamentPosition: "center",
    buttonLabel: "Buka Undangan",
    showNames: true,
    showDate: true,
    showEyebrow: true,
    eyebrowText: "The Wedding of",
  },
  music: {
    defaultTrack: undefined,
    autoPlay: false,
    showPlayer: true,
  },
  layout: {
    borderRadius: "0.75rem",
    maxWidth: "768px",
    spacing: "2rem",
    buttonStyle: "rounded",
    containerStyle: "card",
  },
};
