import type { InvitationData } from "@/app/invitation/[slug]/InvitationClient";

export const templateCards = [
  {
    id: "elegant",
    name: "Elegant Wedding",
    features: "Countdown · Gallery · RSVP · Maps",
    popular: true,
    new: false,
    colors: "from-[#2C2420] to-[#6B4F38]",
    textColor: "text-[#E8D5B0]",
    couples: "Rizky & Salsabila",
    date: "24 · Agustus · 2026",
  },
  {
    id: "minimalist",
    name: "Minimalist",
    features: "Clean · Modern · Timeless",
    popular: false,
    new: false,
    colors: "from-[#F5EFE3] to-[#EDE4D3]",
    textColor: "text-[#4A3728]",
    couples: "Bagas & Nadia",
    date: "12 · Oktober · 2026",
  },
  {
    id: "floral",
    name: "Floral Romance",
    features: "Romantis · Bunga · Feminine",
    popular: false,
    new: true,
    colors: "from-[#F8EDE8] to-[#D9A5A0]",
    textColor: "text-[#4A2820]",
    couples: "Dimas & Putri",
    date: "03 · Maret · 2026",
  },
  {
    id: "dark",
    name: "Dark Luxury",
    features: "Mewah · Gelap · Prestisius",
    popular: false,
    new: false,
    colors: "from-[#1A1410] to-[#2C2018]",
    textColor: "text-[#C9A96E]",
    couples: "Ahmad & Raisya",
    date: "17 · Mei · 2026",
  },
  {
    id: "traditional",
    name: "Traditional Indonesia",
    features: "Batik · Jawa · Berkarakter",
    popular: false,
    new: true,
    colors: "from-[#4A2C10] to-[#C4862E]",
    textColor: "text-[#FFF5E0]",
    couples: "Sekar & Arjuna",
    date: "Sabtu, 7 Juni 2026",
  },
] as const;

export type TemplateId = (typeof templateCards)[number]["id"];

const demoGallery = [
  "/images/gallery-1.jpg",
  "/images/gallery-2.jpg",
  "/images/gallery-3.jpg",
];

export const templateInvitations: Record<TemplateId, InvitationData> = {
  elegant: {
    id: "demo-elegant",
    slug: "elegant",
    brideName: "Rizky",
    groomName: "Salsabila",
    templateId: "elegant",
    eventDate: new Date("2026-08-24"),
    eventTime: "10:00 WIB",
    eventLocation: "The Ritz-Carlton, Jakarta",
    googleMapsUrl: "https://maps.google.com",
    story: "Kisah cinta kami dimulai sejak pertama kali bertemu di kampus.",
    gallery: demoGallery,
    heroImage: "/images/gallery-1.jpg",
    musicUrl: undefined,
  },
  minimalist: {
    id: "demo-minimalist",
    slug: "minimalist",
    brideName: "Bagas",
    groomName: "Nadia",
    templateId: "minimalist",
    eventDate: new Date("2026-10-12"),
    eventTime: "09:00 WIB",
    eventLocation: "Gedung Serbaguna Senayan, Jakarta",
    googleMapsUrl: "https://maps.google.com",
    story: "Dari percakapan sederhana, kami menemukan rumah pada satu sama lain.",
    gallery: demoGallery,
    heroImage: "/images/gallery-2.jpg",
    musicUrl: undefined,
  },
  floral: {
    id: "demo-floral",
    slug: "floral",
    brideName: "Dimas",
    groomName: "Putri",
    templateId: "floral",
    eventDate: new Date("2026-03-03"),
    eventTime: "11:00 WIB",
    eventLocation: "Plataran Dharmawangsa, Jakarta",
    googleMapsUrl: "https://maps.google.com",
    story: "Pertemuan kecil yang tumbuh menjadi janji besar untuk berjalan bersama.",
    gallery: demoGallery,
    heroImage: "/images/gallery-3.jpg",
    musicUrl: undefined,
  },
  dark: {
    id: "demo-dark",
    slug: "dark",
    brideName: "Ahmad",
    groomName: "Raisya",
    templateId: "dark",
    eventDate: new Date("2026-05-17"),
    eventTime: "19:00 WIB",
    eventLocation: "Hotel Indonesia Kempinski, Jakarta",
    googleMapsUrl: "https://maps.google.com",
    story: "Kami memilih saling menetap, dalam doa, usaha, dan rasa syukur.",
    gallery: demoGallery,
    heroImage: "/images/gallery-1.jpg",
    musicUrl: undefined,
  },
  traditional: {
    id: "demo-traditional",
    slug: "traditional",
    brideName: "Sekar",
    groomName: "Arjuna",
    templateId: "traditional",
    eventDate: new Date("2026-06-07"),
    eventTime: "08:00 WIB",
    eventLocation: "Pendopo Agung Royal Ambarrukmo, Yogyakarta",
    googleMapsUrl: "https://maps.google.com",
    story: "Dengan restu keluarga, kami merayakan cinta dalam nuansa tradisi.",
    gallery: demoGallery,
    heroImage: "/images/gallery-2.jpg",
    musicUrl: undefined,
  },
};

export function getTemplateInvitation(slug: string) {
  return templateInvitations[slug as TemplateId];
}
