import type { TemplateConfig } from "../../types/template-engine";

export const baseConfig: TemplateConfig = {
  id: "elegant-wedding",
  name: "Base",
  description: "Base template configuration",
  category: "wedding",
  isPremium: false,
  colors: {
    primary: "#C9A96E",
    secondary: "#4A3728",
    background: "#FAF7F2",
    text: "#2C2420",
    accent: "#E8D5B0",
    surface: "#FFFFFF",
    muted: "#7A5C42",
  },
  fonts: {
    heading: "Cormorant Garamond",
    body: "DM Sans",
    quote: "Great Vibes",
  },
  ornaments: [],
  animation: {
    sectionEntrance: "fade-up",
    staggerDelay: 0.1,
    duration: 0.6,
    parallax: false,
  },
  sections: [
    { type: "hero", enabled: true, label: "Hero", icon: "Heart", customizable: true, fields: ["brideName", "groomName", "heroImage"] },
    { type: "quote", enabled: true, label: "Kutipan", icon: "Quote", customizable: true, fields: [] },
    { type: "countdown", enabled: true, label: "Countdown", icon: "Timer", customizable: true, fields: ["eventDate"] },
    { type: "story", enabled: true, label: "Kisah Cinta", icon: "ScrollText", customizable: true, fields: ["story"] },
    { type: "gallery", enabled: true, label: "Galeri", icon: "ImageIcon", customizable: true, fields: ["gallery"] },
    { type: "event", enabled: true, label: "Acara", icon: "CalendarHeart", customizable: true, fields: ["eventDate", "eventTime", "eventLocation", "googleMapsUrl"] },
    { type: "rsvp", enabled: true, label: "RSVP", icon: "BadgeCheck", customizable: true, fields: [] },
    { type: "wishes", enabled: true, label: "Ucapan", icon: "MessageCircleHeart", customizable: true, fields: [] },
    { type: "gift", enabled: true, label: "Hadiah", icon: "Gift", customizable: true, fields: ["giftBankName", "giftAccountNumber", "giftAccountName"] },
    { type: "footer", enabled: true, label: "Penutup", icon: "PartyPopper", customizable: true, fields: [] },
  ],
  opening: {
    enabled: true,
    backgroundType: "image",
    backgroundValue: "/ornament/pengantin.jpg",
    overlayOpacity: 0.4,
    ornamentPosition: "center",
    buttonLabel: "Buka Undangan",
    buttonStyle: "solid",
    showNames: true,
    showDate: true,
    showEyebrow: true,
    eyebrowText: "The Wedding of",
  },
};
