import type { TemplateSection } from "@/types/template";

export interface TemplateThemePreset {
  key: string;
  label: string;
  description: string;
  preview: string;
  values: {
    primaryColor: string;
    secondaryColor: string;
    backgroundColor: string;
    textColor: string;
    gradientFrom: string;
    gradientTo: string;
    headingFont: string;
    bodyFont: string;
    buttonStyle: "solid" | "outline" | "rounded";
    borderRadius: "0px" | "4px" | "8px" | "16px" | "24px";
    isPremium: boolean;
    category: "wedding" | "birthday" | "graduation" | "custom";
  };
  sections: TemplateSection[];
  opening: {
    eyebrow: string;
    buttonLabel: string;
    ornament: "royal" | "floral" | "minimal";
  };
}

export const templateThemePresets: TemplateThemePreset[] = [
  {
    key: "chara-51-inspired",
    label: "Chara 51 Inspired",
    description: "Royal dark wedding theme dengan gold ornament dan opening cinematic.",
    preview: "radial-gradient(circle at 50% 18%,rgba(220,185,105,0.36),transparent 32%),linear-gradient(145deg,#100c0b,#2b1b16 48%,#070605)",
    values: {
      primaryColor: "#120D0B",
      secondaryColor: "#D9B86C",
      backgroundColor: "#100C0B",
      textColor: "#F7EBDD",
      gradientFrom: "#2A1A15",
      gradientTo: "#080605",
      headingFont: "Playfair Display",
      bodyFont: "DM Sans",
      buttonStyle: "rounded",
      borderRadius: "24px",
      isPremium: true,
      category: "wedding",
    },
    sections: ["opening", "hero", "quote", "countdown", "story", "gallery", "event", "rsvp", "wishes", "gift", "live-streaming", "footer"],
    opening: {
      eyebrow: "The Wedding Of",
      buttonLabel: "Lihat Undangan",
      ornament: "royal",
    },
  },
  {
    key: "floral-romance",
    label: "Floral Romance",
    description: "Tema romantic soft rose dengan aksen floral dan nuansa intimate.",
    preview: "linear-gradient(145deg,#fff7f5,#f2d7d2)",
    values: {
      primaryColor: "#7E4F52",
      secondaryColor: "#D6A0A5",
      backgroundColor: "#FFF8F5",
      textColor: "#3B2928",
      gradientFrom: "#FFF8F5",
      gradientTo: "#F1D8D3",
      headingFont: "Cormorant Garamond",
      bodyFont: "Poppins",
      buttonStyle: "rounded",
      borderRadius: "24px",
      isPremium: true,
      category: "wedding",
    },
    sections: ["opening", "hero", "quote", "countdown", "story", "gallery", "event", "rsvp", "wishes", "footer"],
    opening: {
      eyebrow: "The Wedding Of",
      buttonLabel: "Buka Undangan",
      ornament: "floral",
    },
  },
  {
    key: "minimal-editorial",
    label: "Minimal Editorial",
    description: "Tema clean editorial dengan typography modern dan layout ringan.",
    preview: "linear-gradient(145deg,#ffffff,#eee7dc)",
    values: {
      primaryColor: "#27211D",
      secondaryColor: "#B99A62",
      backgroundColor: "#FAF7F2",
      textColor: "#2C2420",
      gradientFrom: "#FFFFFF",
      gradientTo: "#EEE7DC",
      headingFont: "Playfair Display",
      bodyFont: "Inter",
      buttonStyle: "outline",
      borderRadius: "16px",
      isPremium: false,
      category: "wedding",
    },
    sections: ["opening", "hero", "quote", "countdown", "gallery", "event", "rsvp", "footer"],
    opening: {
      eyebrow: "Wedding Invitation",
      buttonLabel: "View Invitation",
      ornament: "minimal",
    },
  },
  {
    key: "youtube-premiere",
    label: "YouTube Premiere",
    description: "Tema merah-hitam seperti premiere video, cocok untuk undangan modern dan playful.",
    preview: "radial-gradient(circle at 50% 18%,rgba(255,0,0,0.32),transparent 30%),linear-gradient(145deg,#0f0f0f,#2a0505 52%,#050505)",
    values: {
      primaryColor: "#0F0F0F",
      secondaryColor: "#FF0033",
      backgroundColor: "#0A0A0A",
      textColor: "#FFFFFF",
      gradientFrom: "#250505",
      gradientTo: "#050505",
      headingFont: "Montserrat",
      bodyFont: "Inter",
      buttonStyle: "rounded",
      borderRadius: "24px",
      isPremium: false,
      category: "custom",
    },
    sections: ["opening", "hero", "countdown", "gallery", "event", "rsvp", "wishes", "footer"],
    opening: {
      eyebrow: "Premiere Invitation",
      buttonLabel: "Play Undangan",
      ornament: "minimal",
    },
  },
  {
    key: "facebook-classic",
    label: "Facebook Classic",
    description: "Tema biru sosial yang clean, friendly, dan mudah dibaca untuk semua tamu.",
    preview: "linear-gradient(145deg,#1877F2,#0f4fa8 58%,#082b5c)",
    values: {
      primaryColor: "#0B3D91",
      secondaryColor: "#8EC5FF",
      backgroundColor: "#EEF5FF",
      textColor: "#102033",
      gradientFrom: "#1877F2",
      gradientTo: "#082B5C",
      headingFont: "Poppins",
      bodyFont: "Inter",
      buttonStyle: "rounded",
      borderRadius: "16px",
      isPremium: false,
      category: "custom",
    },
    sections: ["opening", "hero", "quote", "countdown", "gallery", "event", "rsvp", "wishes", "footer"],
    opening: {
      eyebrow: "Social Invitation",
      buttonLabel: "Lihat Undangan",
      ornament: "minimal",
    },
  },
  {
    key: "twitter-x-minimal",
    label: "Twitter / X Minimal",
    description: "Tema minimal hitam-putih dengan aksen biru, modern dan tajam.",
    preview: "radial-gradient(circle at 50% 18%,rgba(29,155,240,0.28),transparent 32%),linear-gradient(145deg,#000000,#111827)",
    values: {
      primaryColor: "#000000",
      secondaryColor: "#1D9BF0",
      backgroundColor: "#060606",
      textColor: "#F8FAFC",
      gradientFrom: "#000000",
      gradientTo: "#111827",
      headingFont: "Inter",
      bodyFont: "Inter",
      buttonStyle: "outline",
      borderRadius: "24px",
      isPremium: false,
      category: "custom",
    },
    sections: ["opening", "hero", "countdown", "event", "rsvp", "wishes", "footer"],
    opening: {
      eyebrow: "Now Live",
      buttonLabel: "Open Invite",
      ornament: "minimal",
    },
  },
  {
    key: "adat-jawa-royal",
    label: "Adat Jawa Royal",
    description: "Tema adat Jawa dengan nuansa sogan, gold, dan rasa klasik keraton.",
    preview: "radial-gradient(circle at 50% 18%,rgba(210,169,89,0.32),transparent 34%),linear-gradient(145deg,#2B160E,#6B3D1F 55%,#140A06)",
    values: {
      primaryColor: "#2B160E",
      secondaryColor: "#D6A94F",
      backgroundColor: "#F8F0E3",
      textColor: "#2A1A12",
      gradientFrom: "#6B3D1F",
      gradientTo: "#140A06",
      headingFont: "Cormorant Garamond",
      bodyFont: "DM Sans",
      buttonStyle: "rounded",
      borderRadius: "24px",
      isPremium: true,
      category: "wedding",
    },
    sections: ["opening", "hero", "quote", "countdown", "story", "gallery", "event", "rsvp", "wishes", "gift", "live-streaming", "footer"],
    opening: {
      eyebrow: "Pawiwahan",
      buttonLabel: "Mlebet Undangan",
      ornament: "royal",
    },
  },
  {
    key: "adat-batak-ulos",
    label: "Adat Batak Ulos",
    description: "Tema adat Batak dengan merah, hitam, putih, dan aksen ulos yang tegas.",
    preview: "linear-gradient(145deg,#130707,#8B1E1E 46%,#111111 72%,#F5EFE3)",
    values: {
      primaryColor: "#151010",
      secondaryColor: "#B91C1C",
      backgroundColor: "#F7EFE4",
      textColor: "#211715",
      gradientFrom: "#8B1E1E",
      gradientTo: "#111111",
      headingFont: "Playfair Display",
      bodyFont: "Poppins",
      buttonStyle: "rounded",
      borderRadius: "16px",
      isPremium: true,
      category: "wedding",
    },
    sections: ["opening", "hero", "quote", "countdown", "story", "gallery", "event", "rsvp", "wishes", "gift", "footer"],
    opening: {
      eyebrow: "Horas Invitation",
      buttonLabel: "Buka Undangan",
      ornament: "royal",
    },
  },
  {
    key: "dark-luxury-gold",
    label: "Dark Luxury Gold",
    description: "Tema hitam emas high-end dengan atmosfer ballroom dan typography dramatis.",
    preview: "radial-gradient(circle at 50% 18%,rgba(245,197,92,0.34),transparent 30%),linear-gradient(145deg,#050403,#1f1712 58%,#000000)",
    values: {
      primaryColor: "#090604",
      secondaryColor: "#F1C45D",
      backgroundColor: "#090604",
      textColor: "#FFF5E1",
      gradientFrom: "#241911",
      gradientTo: "#000000",
      headingFont: "Playfair Display",
      bodyFont: "DM Sans",
      buttonStyle: "rounded",
      borderRadius: "24px",
      isPremium: true,
      category: "wedding",
    },
    sections: ["opening", "hero", "quote", "countdown", "story", "gallery", "event", "rsvp", "wishes", "gift", "live-streaming", "footer"],
    opening: {
      eyebrow: "Luxury Wedding",
      buttonLabel: "Enter Invitation",
      ornament: "royal",
    },
  },
  {
    key: "sage-garden-party",
    label: "Sage Garden Party",
    description: "Tema outdoor garden dengan sage green, cream, dan suasana intimate natural.",
    preview: "linear-gradient(145deg,#F7F3EA,#C9D4BE 58%,#7E906F)",
    values: {
      primaryColor: "#4C5E43",
      secondaryColor: "#C8A96A",
      backgroundColor: "#F7F3EA",
      textColor: "#273021",
      gradientFrom: "#F7F3EA",
      gradientTo: "#C9D4BE",
      headingFont: "Cormorant Garamond",
      bodyFont: "DM Sans",
      buttonStyle: "rounded",
      borderRadius: "24px",
      isPremium: true,
      category: "wedding",
    },
    sections: ["opening", "hero", "quote", "countdown", "story", "gallery", "event", "rsvp", "wishes", "gift", "footer"],
    opening: {
      eyebrow: "Garden Wedding",
      buttonLabel: "Buka Undangan",
      ornament: "floral",
    },
  },
  {
    key: "beach-sunset",
    label: "Beach Sunset",
    description: "Tema pantai dengan sunset peach, sand beige, dan vibe destination wedding.",
    preview: "linear-gradient(145deg,#FFB199,#FFDDB8 48%,#5A8CA8)",
    values: {
      primaryColor: "#29546A",
      secondaryColor: "#F0A06D",
      backgroundColor: "#FFF2E4",
      textColor: "#2B3F48",
      gradientFrom: "#FFB199",
      gradientTo: "#5A8CA8",
      headingFont: "Playfair Display",
      bodyFont: "Poppins",
      buttonStyle: "rounded",
      borderRadius: "24px",
      isPremium: true,
      category: "wedding",
    },
    sections: ["opening", "hero", "countdown", "gallery", "event", "rsvp", "wishes", "gift", "footer"],
    opening: {
      eyebrow: "Sunset Wedding",
      buttonLabel: "Open Invitation",
      ornament: "minimal",
    },
  },
  {
    key: "modern-monochrome",
    label: "Modern Monochrome",
    description: "Tema hitam putih editorial, minimal, cocok untuk pasangan modern urban.",
    preview: "linear-gradient(145deg,#F8F8F8,#111111)",
    values: {
      primaryColor: "#111111",
      secondaryColor: "#A3A3A3",
      backgroundColor: "#F8F8F8",
      textColor: "#171717",
      gradientFrom: "#FFFFFF",
      gradientTo: "#D4D4D4",
      headingFont: "Montserrat",
      bodyFont: "Inter",
      buttonStyle: "outline",
      borderRadius: "16px",
      isPremium: false,
      category: "wedding",
    },
    sections: ["opening", "hero", "quote", "gallery", "event", "rsvp", "footer"],
    opening: {
      eyebrow: "Modern Wedding",
      buttonLabel: "View Invitation",
      ornament: "minimal",
    },
  },
  {
    key: "birthday-pop",
    label: "Birthday Pop",
    description: "Tema ulang tahun colorful, fun, dan playful untuk birthday invitation.",
    preview: "radial-gradient(circle at 30% 25%,rgba(255,255,255,0.45),transparent 22%),linear-gradient(145deg,#FF5EA8,#6C63FF 54%,#20D3B8)",
    values: {
      primaryColor: "#6C2BD9",
      secondaryColor: "#FF5EA8",
      backgroundColor: "#FFF7FD",
      textColor: "#281536",
      gradientFrom: "#FF5EA8",
      gradientTo: "#20D3B8",
      headingFont: "Poppins",
      bodyFont: "Inter",
      buttonStyle: "rounded",
      borderRadius: "24px",
      isPremium: false,
      category: "birthday",
    },
    sections: ["opening", "hero", "countdown", "gallery", "event", "rsvp", "wishes", "footer"],
    opening: {
      eyebrow: "Birthday Party",
      buttonLabel: "Join The Party",
      ornament: "minimal",
    },
  },
  {
    key: "graduation-prestige",
    label: "Graduation Prestige",
    description: "Tema wisuda formal dengan navy, gold, dan layout prestisius.",
    preview: "linear-gradient(145deg,#071A33,#123A6B 55%,#D9B86C)",
    values: {
      primaryColor: "#071A33",
      secondaryColor: "#D9B86C",
      backgroundColor: "#F5F0E6",
      textColor: "#091827",
      gradientFrom: "#071A33",
      gradientTo: "#123A6B",
      headingFont: "Playfair Display",
      bodyFont: "Inter",
      buttonStyle: "rounded",
      borderRadius: "16px",
      isPremium: true,
      category: "graduation",
    },
    sections: ["opening", "hero", "quote", "countdown", "gallery", "event", "rsvp", "wishes", "footer"],
    opening: {
      eyebrow: "Graduation Invitation",
      buttonLabel: "Open Invitation",
      ornament: "royal",
    },
  },
  {
    key: "islamic-elegance",
    label: "Islamic Elegance",
    description: "Tema islami elegan dengan emerald, ivory, gold, dan atmosfer sakral.",
    preview: "radial-gradient(circle at 50% 18%,rgba(218,185,105,0.28),transparent 34%),linear-gradient(145deg,#063C35,#0C6B5C 58%,#F8F1E4)",
    values: {
      primaryColor: "#063C35",
      secondaryColor: "#D7B66D",
      backgroundColor: "#F8F1E4",
      textColor: "#102E29",
      gradientFrom: "#063C35",
      gradientTo: "#0C6B5C",
      headingFont: "Cormorant Garamond",
      bodyFont: "DM Sans",
      buttonStyle: "rounded",
      borderRadius: "24px",
      isPremium: true,
      category: "wedding",
    },
    sections: ["opening", "hero", "quote", "countdown", "gallery", "event", "rsvp", "wishes", "gift", "footer"],
    opening: {
      eyebrow: "Bismillahirrahmanirrahim",
      buttonLabel: "Buka Undangan",
      ornament: "royal",
    },
  },
  {
    key: "korean-soft",
    label: "Korean Soft Wedding",
    description: "Tema soft pastel ala Korean wedding: clean, romantic, dan airy.",
    preview: "linear-gradient(145deg,#FFFFFF,#F7DEE4 48%,#D8E7F5)",
    values: {
      primaryColor: "#59464C",
      secondaryColor: "#E7A9B8",
      backgroundColor: "#FFFFFF",
      textColor: "#3A2B30",
      gradientFrom: "#FFFFFF",
      gradientTo: "#F7DEE4",
      headingFont: "Cormorant Garamond",
      bodyFont: "Poppins",
      buttonStyle: "rounded",
      borderRadius: "24px",
      isPremium: true,
      category: "wedding",
    },
    sections: ["opening", "hero", "quote", "countdown", "story", "gallery", "event", "rsvp", "wishes", "footer"],
    opening: {
      eyebrow: "Our Wedding Day",
      buttonLabel: "Open Invitation",
      ornament: "floral",
    },
  },
];

export function getTemplateTheme(themeKey?: string | null) {
  return templateThemePresets.find((theme) => theme.key === themeKey) ?? templateThemePresets[0];
}
