import type { TemplateConfig } from "../../types/template-engine";

export const islamiConfig: TemplateConfig = {
  id: "islami",
  name: "Islami Elegance",
  description: "Template pernikahan Islami dengan nuansa hijau emerald dan emas yang elegan, dilengkapi ayat Al-Quran.",
  category: "islami",
  previewImage: "/images/preview-islami.jpg",
  isPremium: false,
  colors: {
    primary: "#1B5E20",
    secondary: "#D4A84B",
    background: "#F5F0E8",
    text: "#2C2C2C",
    accent: "#81C784",
    surface: "#FFFFFF",
    muted: "#6B8E6B",
  },
  fonts: {
    heading: "Playfair Display",
    body: "DM Sans",
    quote: "Cormorant Garamond",
  },
  ornaments: [
    { id: "masjid-header", type: "svg", position: "header", src: "/ornament/header-03.svg" },
    { id: "islamic-divider", type: "svg", position: "divider", src: "/ornament/header-04.svg" },
    { id: "islamic-corner", type: "svg", position: "corner", src: "/ornament/header-01.svg" },
  ],
  animation: {
    sectionEntrance: "fade-up",
    staggerDelay: 0.1,
    duration: 0.6,
    parallax: false,
  },
  sections: [
    { type: "opening", enabled: true, label: "Pembukaan", icon: "DoorOpen", customizable: true, fields: [] },
    { type: "hero", enabled: true, label: "Hero", icon: "Heart", customizable: true, fields: ["brideName", "groomName", "heroImage"] },
    { type: "quote", enabled: true, label: "Bismillah", icon: "Quote", customizable: true, fields: [] },
    { type: "countdown", enabled: true, label: "Countdown", icon: "Timer", customizable: true, fields: ["eventDate"] },
    { type: "story", enabled: true, label: "Kisah", icon: "ScrollText", customizable: true, fields: ["story"] },
    { type: "gallery", enabled: true, label: "Galeri", icon: "ImageIcon", customizable: true, fields: ["gallery"] },
    { type: "event", enabled: true, label: "Akad & Resepsi", icon: "CalendarHeart", customizable: true, fields: ["eventDate", "eventTime", "eventLocation", "googleMapsUrl"] },
    { type: "rsvp", enabled: true, label: "Konfirmasi", icon: "BadgeCheck", customizable: true, fields: [] },
    { type: "wishes", enabled: true, label: "Doa & Ucapan", icon: "MessageCircleHeart", customizable: true, fields: [] },
    { type: "gift", enabled: true, label: "Hadiah", icon: "Gift", customizable: true, fields: ["giftBankName", "giftAccountNumber", "giftAccountName"] },
    { type: "live-streaming", enabled: true, label: "Live Streaming", icon: "Radio", customizable: true, fields: [] },
    { type: "footer", enabled: true, label: "Penutup", icon: "PartyPopper", customizable: true, fields: [] },
  ],
  opening: {
    enabled: true,
    backgroundType: "gradient",
    backgroundValue: "linear-gradient(160deg, #1B5E20, #0D3B0D)",
    overlayOpacity: 0.3,
    ornamentPosition: "top",
    buttonLabel: "Buka Undangan",
    buttonStyle: "rounded",
    showNames: true,
    showDate: true,
    showEyebrow: true,
    eyebrowText: "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيم",
  },
  border: { radius: "1rem", style: "rounded" },
  buttonStyle: "rounded",
  gradientFrom: "#1B5E20",
  gradientTo: "#0D3B0D",
};
