import type { ThemeConfig } from "../../types/template";

export const islamiV2Config: ThemeConfig = {
  id: "islami",
  name: "Islami",
  description: "Tema hijau emerald dengan nuansa Islami yang syahdu dan elegan.",
  category: "islami",
  version: "1.0.0",
  author: "Kundangan",
  previewImage: "/images/preview-islami.jpg",
  isPremium: false,
  colors: {
    primary: "#1B5E20",
    secondary: "#D4A84B",
    background: "#F5F0E8",
    text: "#2C2C2C",
    accent: "#81C784",
    surface: "#FFFFFF",
    muted: "#6B8E6B",
  },
  fonts: {
    heading: "Playfair Display",
    body: "DM Sans",
    quote: "Cormorant Garamond",
  },
  animations: {
    cover: "fade-up",
    content: "fade-up",
    gallery: "fade-up",
    couple: "fade-up",
  },
  decorations: {
    enabled: ["flower-corner", "ornament"],
    intensity: "subtle",
    color: "#D4A84B",
  },
  sections: [
    { type: "cover", enabled: true, label: "Cover", order: 0 },
    { type: "couple", enabled: true, label: "Kedua Mempelai", order: 1 },
    { type: "countdown", enabled: true, label: "Hitung Mundur", order: 2 },
    { type: "story", enabled: true, label: "Kisah Kami", order: 3 },
    { type: "gallery", enabled: true, label: "Galeri", order: 4 },
    { type: "event", enabled: true, label: "Acara", order: 5 },
    { type: "rsvp", enabled: true, label: "Konfirmasi", order: 6 },
    { type: "wish", enabled: true, label: "Ucapan", order: 7 },
    { type: "gift", enabled: true, label: "Hadiah", order: 8 },
    { type: "footer", enabled: true, label: "Penutup", order: 9 },
  ],
  cover: {
    backgroundType: "gradient",
    backgroundValue: "linear-gradient(160deg, #1B5E20, #0D3B0D)",
    overlayOpacity: 0.3,
    ornamentPosition: "top",
    buttonLabel: "Buka Undangan",
    showNames: true,
    showDate: true,
    showEyebrow: true,
    eyebrowText: "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيم",
  },
  music: {
    defaultTrack: undefined,
    autoPlay: false,
    showPlayer: true,
  },
  layout: {
    borderRadius: "1rem",
    maxWidth: "768px",
    spacing: "2rem",
    buttonStyle: "rounded",
    containerStyle: "card",
  },
};
