import type { TemplateConfig } from "../../types/template-engine";

export const batakTobaConfig: TemplateConfig = {
  id: "batak-toba",
  name: "Batak Toba",
  description: "Template adat Batak Toba dengan warna merah maroon, emas, dan motif ulos yang khas.",
  category: "adat-batak",
  previewImage: "/images/preview-batak.jpg",
  isPremium: true,
  colors: {
    primary: "#C62828",
    secondary: "#8B0000",
    background: "#1A0A0A",
    text: "#FFF8F0",
    accent: "#D4A84B",
    surface: "#2D1515",
    muted: "#A0522D",
  },
  fonts: {
    heading: "Playfair Display",
    body: "DM Sans",
    quote: "Cormorant Garamond",
  },
  ornaments: [
    { id: "ulos-header", type: "svg", position: "header", src: "/ornament/batak-header.svg" },
    { id: "gorga-divider", type: "svg", position: "divider", src: "/ornament/batak-divider.svg" },
    { id: "ulos-footer", type: "svg", position: "footer", src: "/ornament/batak-footer.svg" },
    { id: "gorga-corner", type: "svg", position: "corner", src: "/ornament/batak-corner.svg" },
    { id: "ulos-pattern", type: "pattern", position: "background", className: "bg-repeat opacity-5" },
  ],
  animation: {
    sectionEntrance: "fade-up",
    staggerDelay: 0.12,
    duration: 0.7,
    parallax: false,
  },
  sections: [
    { type: "opening", enabled: true, label: "Pembukaan", icon: "DoorOpen", customizable: true, fields: [] },
    { type: "hero", enabled: true, label: "Hero", icon: "Heart", customizable: true, fields: ["brideName", "groomName", "heroImage"] },
    { type: "quote", enabled: true, label: "Dongan Tu Ulaon", icon: "Quote", customizable: true, fields: [] },
    { type: "countdown", enabled: true, label: "Countdown", icon: "Timer", customizable: true, fields: ["eventDate"] },
    { type: "story", enabled: true, label: "Turiturian", icon: "ScrollText", customizable: true, fields: ["story"] },
    { type: "gallery", enabled: true, label: "Galeri", icon: "ImageIcon", customizable: true, fields: ["gallery"] },
    { type: "event", enabled: true, label: "Ulaon", icon: "CalendarHeart", customizable: true, fields: ["eventDate", "eventTime", "eventLocation", "googleMapsUrl"] },
    { type: "rsvp", enabled: true, label: "RSVP", icon: "BadgeCheck", customizable: true, fields: [] },
    { type: "wishes", enabled: true, label: "Ucapan", icon: "MessageCircleHeart", customizable: true, fields: [] },
    { type: "gift", enabled: true, label: "Amplop", icon: "Gift", customizable: true, fields: ["giftBankName", "giftAccountNumber", "giftAccountName"] },
    { type: "footer", enabled: true, label: "Penutup", icon: "PartyPopper", customizable: true, fields: [] },
  ],
  opening: {
    enabled: true,
    backgroundType: "gradient",
    backgroundValue: "linear-gradient(160deg, #1A0A0A, #C62828)",
    overlayOpacity: 0.35,
    ornamentPosition: "center",
    buttonLabel: "Bungka Undangan",
    buttonStyle: "solid",
    showNames: true,
    showDate: true,
    showEyebrow: true,
    eyebrowText: "Dongan Tu Ulaon",
  },
  border: { radius: "0.5rem", style: "rounded" },
  buttonStyle: "solid",
  gradientFrom: "#1A0A0A",
  gradientTo: "#C62828",
};
