import type { ThemeConfig } from "../../types/template";

export const batakTobaV2Config: ThemeConfig = {
  id: "batak-toba",
  name: "Batak Toba",
  description: "Tema maroon dan emas yang mencerminkan kehangatan dan kehormatan adat Batak Toba.",
  category: "adat-batak",
  version: "1.0.0",
  author: "Kundangan",
  previewImage: "/images/preview-batak.jpg",
  isPremium: true,
  colors: {
    primary: "#C62828",
    secondary: "#8B0000",
    background: "#1A0A0A",
    text: "#FFF8F0",
    accent: "#D4A84B",
    surface: "#2D1515",
    muted: "#A0522D",
  },
  fonts: {
    heading: "Playfair Display",
    body: "DM Sans",
    quote: "Cormorant Garamond",
  },
  animations: {
    cover: "fade-up",
    content: "fade-up",
    gallery: "slide-left",
    couple: "fade-up",
  },
  decorations: {
    enabled: ["flower-corner", "ornament", "sparkle"],
    intensity: "heavy",
    color: "#D4A84B",
  },
  sections: [
    { type: "cover", enabled: true, label: "Cover", order: 0 },
    { type: "couple", enabled: true, label: "Pasangan", order: 1 },
    { type: "countdown", enabled: true, label: "Hitung Mundur", order: 2 },
    { type: "story", enabled: true, label: "Cerita", order: 3 },
    { type: "gallery", enabled: true, label: "Galeri", order: 4 },
    { type: "event", enabled: true, label: "Acara", order: 5 },
    { type: "rsvp", enabled: true, label: "Konfirmasi", order: 6 },
    { type: "wish", enabled: true, label: "Ucapan", order: 7 },
    { type: "gift", enabled: true, label: "Hadiah", order: 8 },
    { type: "footer", enabled: true, label: "Penutup", order: 9 },
  ],
  cover: {
    backgroundType: "gradient",
    backgroundValue: "linear-gradient(160deg, #1A0A0A, #C62828)",
    overlayOpacity: 0.35,
    ornamentPosition: "center",
    buttonLabel: "Bungka Undangan",
    showNames: true,
    showDate: true,
    showEyebrow: true,
    eyebrowText: "Dongan Tu Ulaon",
  },
  music: {
    defaultTrack: undefined,
    autoPlay: false,
    showPlayer: true,
  },
  layout: {
    borderRadius: "0.5rem",
    maxWidth: "768px",
    spacing: "2rem",
    buttonStyle: "rounded",
    containerStyle: "card",
  },
};
