import type { TemplateConfig } from "../../types/template-engine";

export const jawaConfig: TemplateConfig = {
  id: "jawa",
  name: "Adat Jawa",
  description: "Template pernikahan adat Jawa dengan nuansa sogan coklat keemasan dan motif batik klasik.",
  category: "adat-jawa",
  previewImage: "/images/preview-jawa.jpg",
  isPremium: true,
  colors: {
    primary: "#8B6914",
    secondary: "#4A2C10",
    background: "#F5EFE3",
    text: "#3E2723",
    accent: "#D4A84B",
    surface: "#FFF8F0",
    muted: "#A67B5B",
  },
  fonts: {
    heading: "Playfair Display",
    body: "DM Sans",
    quote: "Cormorant Garamond",
  },
  ornaments: [
    { id: "batik-header", type: "svg", position: "header", src: "/ornament/header-01.svg" },
    { id: "batik-divider", type: "svg", position: "divider", src: "/ornament/header-04.svg" },
    { id: "batik-footer", type: "svg", position: "footer", src: "/ornament/header-03.svg" },
    { id: "batik-corner", type: "svg", position: "corner", src: "/ornament/header-11.svg" },
    { id: "batik-pattern", type: "pattern", position: "background", className: "bg-repeat opacity-3" },
  ],
  animation: {
    sectionEntrance: "fade-up",
    staggerDelay: 0.12,
    duration: 0.7,
    parallax: true,
  },
  sections: [
    { type: "opening", enabled: true, label: "Pambuka", icon: "DoorOpen", customizable: true, fields: [] },
    { type: "hero", enabled: true, label: "Hero", icon: "Heart", customizable: true, fields: ["brideName", "groomName", "heroImage"] },
    { type: "quote", enabled: true, label: "Pambagyo", icon: "Quote", customizable: true, fields: [] },
    { type: "countdown", enabled: true, label: "Countdown", icon: "Timer", customizable: true, fields: ["eventDate"] },
    { type: "story", enabled: true, label: "Babat", icon: "ScrollText", customizable: true, fields: ["story"] },
    { type: "gallery", enabled: true, label: "Galeri", icon: "ImageIcon", customizable: true, fields: ["gallery"] },
    { type: "event", enabled: true, label: "Panggih", icon: "CalendarHeart", customizable: true, fields: ["eventDate", "eventTime", "eventLocation", "googleMapsUrl"] },
    { type: "rsvp", enabled: true, label: "Konfirmasi", icon: "BadgeCheck", customizable: true, fields: [] },
    { type: "wishes", enabled: true, label: "Ucapan", icon: "MessageCircleHeart", customizable: true, fields: [] },
    { type: "gift", enabled: true, label: "Sumbangan", icon: "Gift", customizable: true, fields: ["giftBankName", "giftAccountNumber", "giftAccountName"] },
    { type: "footer", enabled: true, label: "Panutup", icon: "PartyPopper", customizable: true, fields: [] },
  ],
  opening: {
    enabled: true,
    backgroundType: "image",
    backgroundValue: "/ornament/pengantin.jpg",
    overlayOpacity: 0.45,
    ornamentPosition: "center",
    buttonLabel: "Bikak Undangan",
    buttonStyle: "solid",
    showNames: true,
    showDate: true,
    showEyebrow: true,
    eyebrowText: "Wilujeng Sumping",
  },
  border: { radius: "0.75rem", style: "rounded" },
  buttonStyle: "solid",
  gradientFrom: "#F5EFE3",
  gradientTo: "#E8D5B0",
};
