import type { ThemeConfig } from "../../types/template";

export const jawaV2Config: ThemeConfig = {
  id: "jawa",
  name: "Adat Jawa",
  description: "Tema adat Jawa dengan warna sogan cokelat keemasan dan nuansa tradisional yang kental.",
  category: "adat-jawa",
  version: "1.0.0",
  author: "Kundangan",
  previewImage: "/images/preview-jawa.jpg",
  isPremium: true,
  colors: {
    primary: "#8B6914",
    secondary: "#4A2C10",
    background: "#F5EFE3",
    text: "#3E2723",
    accent: "#D4A84B",
    surface: "#FFF8F0",
    muted: "#A67B5B",
  },
  fonts: {
    heading: "Playfair Display",
    body: "DM Sans",
    quote: "Cormorant Garamond",
  },
  animations: {
    cover: "fade-up",
    content: "fade-up",
    gallery: "slide-right",
    couple: "zoom-in",
  },
  decorations: {
    enabled: ["flower-corner", "ornament", "sparkle"],
    intensity: "medium",
    color: "#D4A84B",
  },
  sections: [
    { type: "cover", enabled: true, label: "Cover", order: 0 },
    { type: "couple", enabled: true, label: "Kedua Mempelai", order: 1 },
    { type: "countdown", enabled: true, label: "Hitung Mundur", order: 2 },
    { type: "story", enabled: true, label: "Cerita Kami", order: 3 },
    { type: "gallery", enabled: true, label: "Galeri", order: 4 },
    { type: "event", enabled: true, label: "Acara", order: 5 },
    { type: "rsvp", enabled: true, label: "Konfirmasi", order: 6 },
    { type: "wish", enabled: true, label: "Ucapan", order: 7 },
    { type: "gift", enabled: true, label: "Hadiah", order: 8 },
    { type: "footer", enabled: true, label: "Penutup", order: 9 },
  ],
  cover: {
    backgroundType: "image",
    backgroundValue: "/ornament/pengantin.jpg",
    overlayOpacity: 0.45,
    ornamentPosition: "center",
    buttonLabel: "Bikak Undangan",
    showNames: true,
    showDate: true,
    showEyebrow: true,
    eyebrowText: "Wilujeng Sumping",
  },
  music: {
    defaultTrack: undefined,
    autoPlay: false,
    showPlayer: true,
  },
  layout: {
    borderRadius: "0.75rem",
    maxWidth: "768px",
    spacing: "2rem",
    buttonStyle: "rounded",
    containerStyle: "card",
  },
};
