import type { TemplateConfig } from "../../types/template-engine";

export const luxuryModernConfig: TemplateConfig = {
  id: "luxury-modern",
  name: "Luxury Modern",
  description: "Template modern mewah dengan aksen hitam-putih dan garis bersih. Cocok untuk pernikahan kontemporer.",
  category: "luxury",
  previewImage: "/images/preview-luxury.jpg",
  isPremium: true,
  colors: {
    primary: "#1A1A1A",
    secondary: "#C9A96E",
    background: "#FFFFFF",
    text: "#1A1A1A",
    accent: "#E8D5B0",
    surface: "#F8F6F3",
    muted: "#6B6B6B",
  },
  fonts: {
    heading: "Cormorant Garamond",
    body: "Inter",
    quote: "DM Sans",
  },
  ornaments: [
    { id: "minimal-header", type: "svg", position: "header", src: "/ornament/header-11.svg" },
    { id: "gold-line", type: "svg", position: "divider", svg: "<svg width='60' height='2' viewBox='0 0 60 2'><line x1='0' y1='1' x2='60' y2='1' stroke='#C9A96E' stroke-width='1'/></svg>" },
  ],
  animation: {
    sectionEntrance: "fade-in",
    staggerDelay: 0.08,
    duration: 0.5,
    parallax: false,
  },
  sections: [
    { type: "opening", enabled: true, label: "Opening", icon: "DoorOpen", customizable: true, fields: [] },
    { type: "hero", enabled: true, label: "Hero", icon: "Heart", customizable: true, fields: ["brideName", "groomName", "heroImage"] },
    { type: "countdown", enabled: true, label: "Countdown", icon: "Timer", customizable: true, fields: ["eventDate"] },
    { type: "story", enabled: true, label: "Our Story", icon: "ScrollText", customizable: true, fields: ["story"] },
    { type: "gallery", enabled: true, label: "Gallery", icon: "ImageIcon", customizable: true, fields: ["gallery"] },
    { type: "event", enabled: true, label: "Event", icon: "CalendarHeart", customizable: true, fields: ["eventDate", "eventTime", "eventLocation", "googleMapsUrl"] },
    { type: "rsvp", enabled: true, label: "RSVP", icon: "BadgeCheck", customizable: true, fields: [] },
    { type: "wishes", enabled: true, label: "Wishes", icon: "MessageCircleHeart", customizable: true, fields: [] },
    { type: "gift", enabled: true, label: "Gift", icon: "Gift", customizable: true, fields: ["giftBankName", "giftAccountNumber", "giftAccountName"] },
    { type: "footer", enabled: true, label: "Closing", icon: "PartyPopper", customizable: true, fields: [] },
  ],
  opening: {
    enabled: true,
    backgroundType: "color",
    backgroundValue: "#FFFFFF",
    overlayOpacity: 0,
    ornamentPosition: "bottom",
    buttonLabel: "Open Invitation",
    buttonStyle: "outline",
    showNames: true,
    showDate: true,
    showEyebrow: true,
    eyebrowText: "We're Getting Married",
  },
  border: { radius: "0.375rem", style: "sharp" },
  buttonStyle: "outline",
  gradientFrom: "#FFFFFF",
  gradientTo: "#F8F6F3",
};
