import type { ThemeConfig } from "../../types/template";

export const luxuryModernV2Config: ThemeConfig = {
  id: "luxury-modern",
  name: "Luxury Modern",
  description: "Tema putih bersih dengan aksen emas minimalis — elegan, simpel, dan timeless.",
  category: "modern",
  version: "1.0.0",
  author: "Kundangan",
  previewImage: "/images/preview-luxury.jpg",
  isPremium: true,
  colors: {
    primary: "#1A1A1A",
    secondary: "#C9A96E",
    background: "#FFFFFF",
    text: "#1A1A1A",
    accent: "#E8D5B0",
    surface: "#F8F6F3",
    muted: "#6B6B6B",
  },
  fonts: {
    heading: "Cormorant Garamond",
    body: "Inter",
    quote: "DM Sans",
  },
  animations: {
    cover: "fade-up",
    content: "zoom-in",
    gallery: "slide-left",
    couple: "fade-up",
  },
  decorations: {
    enabled: ["ornament"],
    intensity: "subtle",
    color: "#C9A96E",
  },
  sections: [
    { type: "cover", enabled: true, label: "Cover", order: 0 },
    { type: "couple", enabled: true, label: "Kedua Mempelai", order: 1 },
    { type: "countdown", enabled: true, label: "Countdown", order: 2 },
    { type: "story", enabled: true, label: "Our Story", order: 3 },
    { type: "gallery", enabled: true, label: "Gallery", order: 4 },
    { type: "event", enabled: true, label: "Event", order: 5 },
    { type: "rsvp", enabled: true, label: "RSVP", order: 6 },
    { type: "wish", enabled: true, label: "Wishes", order: 7 },
    { type: "gift", enabled: true, label: "Gift", order: 8 },
    { type: "footer", enabled: true, label: "Footer", order: 9 },
  ],
  cover: {
    backgroundType: "color",
    backgroundValue: "#FFFFFF",
    overlayOpacity: 0,
    ornamentPosition: "bottom",
    buttonLabel: "Open Invitation",
    showNames: true,
    showDate: true,
    showEyebrow: true,
    eyebrowText: "We're Getting Married",
  },
  music: {
    defaultTrack: undefined,
    autoPlay: false,
    showPlayer: true,
  },
  layout: {
    borderRadius: "0.375rem",
    maxWidth: "768px",
    spacing: "2rem",
    buttonStyle: "outline",
    containerStyle: "full",
  },
};
